services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-booking:5432/postgres
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres-booking
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - postgres-booking
    networks:
      - booking-net

  postgres-booking:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - "booking-volume:/var/lib/postgresql/data"
    networks:
      - booking-net

volumes:
  booking-volume:
    external: true

networks:
  adminerdev:
    external: true
  booking-net:
    external: true
